service: serverless-lambda-boilerplate
frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  apiGateway:
    shouldStartNameWithService: true

package:
 exclude:
   - .*
   - src
   - package.json
   - README.md
   - serverless.yml
   - tsconfig.json
   - yarn.lock
   - pXKf

functions:
  public:
    handler: dist/public.handler
    events:
      - http:
          path: '/'
          method: get
          integration: lambda-proxy

